-

  name: Launch ec2-instances using ansible from given hosts

  hosts: linux
  gather_facts: True

  tasks:

    -

      name: Launch Ec2-instances

      ec2:
        instance_type: t2.micro
        count: 1
        group: ansibledemo
        image: ami-0cfee17793b08a293
        wait: yes
        region: us-east-1
        key_name: ansiblevirginia
      register: ec2   
    - 
      name: Add the newly created host
      debug: msg="Allocated IP inside the VPC hosts is {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
    -
      name: add it in host file
      lineinfile:
          path: "/etc/ansible/hosts"
          insertafter: "[launched]" 
          line: "{{ item.public_ip }}"  
      with_items: "{{ ec2.instances }}"
    - 
      name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_ip }}"
          port: 22
          state: started
      with_items: "{{ ec2.instances }}"
   
