---
- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: Install apache webserver
      sudo: true
      apt: pkg={{ item }} state=latest update_cache=true
      ignore_errors: True
      with_items:
        - apache2

    - name: Install support for PHP, Ruby and Python
      sudo: true
      apt: pkg={{ item }} state=latest update_cache=true
      ignore_errors: True
      with_items:
        - libapache2-mod-php5
        - libapache2-mod-passenger
        - libapache2-mod-wsgi

    - name: Enable apache2 modules
      sudo: true
      shell: "{{ item }}"
      with_items:
        - a2enmod rewrite
        - a2enmod ssl
        - a2enmod expires
        - a2enmod headers
        - a2enmod proxy
        - a2enmod proxy_http
        - /etc/init.d/apache2 restart

    - name: Ensure apache2 is running
      service: name=apache2 state=started enabled=yes