---
- name: Install MySQL database server
  hosts: test
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [database]
  tasks:
        - name: Update the software package repository
          yum:
                update_cache: yes

        - name: Install MySQL
          package:
                name: "{{ item }}"
                state: latest

          with_items:
              - mysql-server
              - mysql-client
              - python-mysqldb


- name: Download sources
      get_url:
        url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        dest: /opt/mysql

   - name: Install package
     yum:
       name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm
       state: present


   - name: Install MySQL
     yum: name=mysql-server state=installed